[package]
name = "c-lightning-http-plugin"
version = "0.1.0"
authors = ["Keagan McClelland <keagan@helix.local>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = "0.13.2"
tokio = { features = ["full"], version = "0.2.13" }
lazy_async_pool = "0.2.1"
